---
# podDisruptionBudget: ensure that normal GKE/k8s maintenance events
# do not reduce the pod count below the minimum necessary to serve.
# Note that this is advisory: unplanned/emergency node deaths may
# still impair or destroy the cluster.
{{- if .Capabilities.APIVersions.Has "policy/v1" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: "{{ .Release.Name }}-pdb"
  labels:
    app: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
  maxUnavailable: {{ .Values.deploy.podDisruptionBudget.maxUnavailable }}
