name: Docker Build

on:
  release:
    types: [published]

jobs:
  docker_build:
    strategy:
      matrix:
        pgpool_version:
          - 4.5.4
          - 4.4.9
          - 4.3.12
          - 4.2.19
          - 4.1.22
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set output
        id: vars
        run: |
          REF_NAME=${{ github.ref_name }}
          echo "release_version=${REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}"
          file: ./Dockerfile
          build-args: PGPOOL_VERSION=${{matrix.pgpool_version}}
          pull: true
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pgpool-cloudsql:${{ steps.vars.outputs.release_version }}-${{matrix.pgpool_version}}
